{
 "title": "SFORIN02",
 "description": "development dashboard",
 "tags": [ "Orin" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT uptime FROM sfOrinMonitoring.sfvis01 ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Board Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT hostname, model, ip_address FROM sfOrinMonitoring.sfvis01 ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Board Hardware Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 4 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT p_number, id, cudnn, module, serial_number, tensorrt, vulkan FROM sfOrinMonitoring.sfvis01 ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT GPU FROM sfOrinMonitoring.sfvis01 ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT CPU1, CPU2, CPU3, CPU4, CPU5, CPU6 FROM sfOrinMonitoring.sfvis01 ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Fan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT `Fan pwmfan0` FROM sfOrinMonitoring.sfvis01 LIMIT 50 "
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT RAM, SWAP FROM sfOrinMonitoring.sfvis01 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT disk_available_gb FROM sfOrinMonitoring.sfvis01 ORDER BY time DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Sensor Temperatures",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT `Temp CPU`, `Temp GPU`, `Temp SOC0`, `Temp SOC1`, `Temp SOC2`, `Temp tj` FROM sfOrinMonitoring.sfvis01 ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "options": {
    "content": "\n<div style=\"text-align: center;\">\n  <img src=\"http://sfgrafana.sf.local/Full_Transparent_Background.png\" alt=\"WSU Tech - Smart Factory\" style=\"max-width: 100%; max-height: 100%;\">\n</div>\n\n"
   },
   "targets": [
    { "dataset": "mysql" }
   ]
  }
 ]
}